services:
  app:
    image: courya-backend
    build:
      context: .
      dockerfile: Dockerfile

    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT}
    volumes:
      - .:/app
    
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  db:
    image: postgres:16.3
    container_name: simple-pos-db
    command: -p ${SQL_DB_PORT}
    volumes:
      - simple-pos-db:/var/lib/postgresql/data
    ports:
      - "${SQL_DB_PORT}:${SQL_DB_PORT}"
    environment:
      - POSTGRES_DB=${SQL_DB_NAME}
      - POSTGRES_USER=${SQL_DB_USERNAME}
      - POSTGRES_PASSWORD=${SQL_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_DB_USERNAME} -d ${SQL_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - mynetwork




volumes:
  redis:
    driver: local
  simple-pos-db:

networks:
  mynetwork:
    driver: bridge
